<template>
  <section class="profile-section profile-section--first space-management">
    <header class="space-management__head"><div><p>本机数据</p><h3>存储与清理</h3><small>了解占用，安全整理不再需要的附件。</small></div><button class="text-btn" type="button" :disabled="loading" @click="scan">{{ loading ? '正在扫描…' : report ? '重新扫描' : '扫描空间' }}</button></header>
      <section v-if="!report" class="storage-dashboard storage-dashboard--empty"><span class="storage-dashboard__empty-icon"><HardDrive :size="24" /></span><div><strong>检查本机存储</strong><p>扫描只读取数据，不会修改或删除任何文件。</p></div><button class="small-btn" type="button" :disabled="loading" @click="scan">{{ loading ? '正在扫描…' : '开始扫描' }}</button></section>
    <template v-else>
      <section class="storage-dashboard" aria-live="polite"><div class="storage-dashboard__total"><span class="storage-dashboard__total-icon"><Database :size="20" /></span><span><small>应用已占用</small><strong>{{ bytes(report.totalBytes) }}</strong><em>任务、附件、恢复点和个人资料</em></span></div><div class="storage-dashboard__next" :class="{ 'has-work': report.orphanAttachments.length }"><span><small>{{ report.orphanAttachments.length ? '可安全整理' : report.quarantinedAttachments.length ? '清理站待处理' : '空间状态' }}</small><strong>{{ report.orphanAttachments.length ? `可释放 ${bytes(reclaimableBytes)}` : report.quarantinedAttachments.length ? `${report.quarantinedAttachments.length} 项文件可恢复` : '没有待处理附件' }}</strong><em>{{ report.orphanAttachments.length ? `${report.orphanAttachments.length} 项未引用附件，先移入清理站再决定是否删除。` : report.quarantinedAttachments.length ? '文件仍在本机，永久删除前可随时恢复。' : '任务、备注和回收站引用均已检查。' }}</em></span><button v-if="report.orphanAttachments.length" class="small-btn" type="button" :disabled="acting" @click="openBrowser('orphan')">开始整理</button><button v-else-if="report.quarantinedAttachments.length" class="small-btn" type="button" :disabled="acting" @click="openBrowser('quarantine')">查看清理站</button></div></section>
      <section v-if="report.orphanAttachments.length || report.quarantinedAttachments.length || report.backupBytes || report.migrationBackups.length" class="storage-work-queue" aria-label="数据维护队列"><article v-if="report.orphanAttachments.length" class="storage-work-card storage-work-card--orphan"><span class="storage-work-card__icon"><FolderArchive :size="19" /></span><div><strong>待处理附件</strong><small>{{ report.orphanAttachments.length }} 项 · {{ bytes(report.orphanBytes) }}<template v-if="orphanTypeSummary"> · {{ orphanTypeSummary }}</template></small><p>尚未被任何任务、备注或回收站引用。</p></div><span class="storage-work-card__actions"><button class="text-btn" type="button" @click="openBrowser('orphan')">查看文件</button><button class="small-btn" type="button" :disabled="acting" @click="quarantineAll">移入清理站</button></span></article><article v-if="report.quarantinedAttachments.length" class="storage-work-card storage-work-card--quarantine"><span class="storage-work-card__icon"><ArchiveRestore :size="19" /></span><div><strong>清理站</strong><small>{{ report.quarantinedAttachments.length }} 项 · {{ bytes(report.quarantinedBytes) }} · 可恢复</small><p>确认永久删除后，才会真正释放本机空间。</p></div><span class="storage-work-card__actions"><button class="text-btn" type="button" @click="openBrowser('quarantine')">查看文件</button><button class="text-btn" type="button" :disabled="acting" @click="restoreAll">全部恢复</button><button class="text-btn danger" type="button" :disabled="acting" @click="requestPurge(report.quarantinedAttachments)">永久删除</button></span></article><article v-if="report.backupBytes" class="storage-work-card"><span class="storage-work-card__icon"><ShieldCheck :size="19" /></span><div><strong>本机恢复点</strong><small>{{ bytes(report.backupBytes) }} · 可恢复当前数据</small><p>恢复点包含任务、附件和头像，在“备份与恢复”中创建、恢复或删除。</p></div><span class="storage-work-card__actions"><button class="small-btn" type="button" @click="$emit('open-security')">管理恢复点</button></span></article><article v-if="report.migrationBackups.length" class="storage-work-card storage-work-card--orphan"><span class="storage-work-card__icon"><HardDrive :size="19" /></span><div><strong>历史迁移备份</strong><small>{{ report.migrationBackups.length }} 项 · {{ bytes(report.migrationBackupBytes) }}</small><p>应用升级前自动保留的兼容性副本；确认不再需要旧版本回退后可永久删除。</p></div><span class="storage-work-card__actions"><button class="text-btn" type="button" @click="migrationBrowserOpen = true">查看文件</button><button class="text-btn danger" type="button" :disabled="acting" @click="requestMigrationPurge(report.migrationBackups)">永久删除</button></span></article></section>
      <p v-else class="storage-dashboard__healthy"><ShieldCheck :size="17" />附件引用状态正常，暂时没有可整理的文件。</p>
      <div v-if="report.missingReferences.length" class="storage-warning">发现 {{ report.missingReferences.length }} 个失效引用：相关文件可能已被手动移走。原任务数据会保留，扫描不会自动修改它。</div>
      <details class="storage-details"><summary><span><Database :size="16" /><strong>空间构成</strong><small>{{ categories.length }} 类本机数据</small></span><span>查看明细</span></summary><div class="storage-breakdown" aria-label="本机空间分类"><div v-for="category in categories" :key="category.id" class="storage-breakdown__item" :class="{ 'is-reclaimable': category.reclaimable }"><span class="storage-breakdown__icon"><component :is="category.icon" :size="16" /></span><span><strong>{{ category.label }}</strong><small>{{ category.description }}</small></span><b>{{ bytes(category.bytes) }}</b></div></div></details>
    </template>
    <details class="storage-details storage-details--preferences"><summary><span><Trash2 :size="16" /><strong>垃圾桶保留</strong><small>到期的删除项会在本机自动清理</small></span><span>{{ store.settings.trashRetentionDays }} 天</span></summary><label class="storage-retention"><span>保留时长</span><select :value="store.settings.trashRetentionDays" @change="store.updateSettings({ trashRetentionDays: Number($event.target.value) })"><option v-for="day in retentionDays" :key="day" :value="day">{{ day }} 天</option></select></label></details>
  </section>
  <ImageLightbox :visible="previewOpen" :images="previewImages" :start-index="previewIndex" @close="previewOpen = false" />
  <Teleport to="body">
    <div v-if="browserOpen" class="storage-browser-layer" @keydown.esc.stop="closeBrowser">
      <button class="storage-browser-layer__scrim" type="button" aria-label="关闭附件查看器" @click="closeBrowser"></button>
      <section class="storage-browser storage-browser--with-summary" :class="{ 'is-quarantine': browserTab === 'quarantine' }" role="dialog" aria-modal="true" aria-labelledby="storage-browser-title">
        <header class="storage-browser__hero"><span class="storage-browser__hero-icon"><ArchiveRestore v-if="browserTab === 'quarantine'" :size="21" /><FolderArchive v-else :size="21" /></span><div class="storage-browser__hero-copy"><span>附件维护</span><h2 id="storage-browser-title">{{ browserTab === 'orphan' ? '待处理附件' : '清理站' }}</h2><small>{{ browserTab === 'orphan' ? '先审阅，再移入可恢复的清理站' : '为文件保留一次反悔机会，再决定是否释放空间' }}</small></div><div class="storage-browser__hero-metric"><strong>{{ bytes(browserBytes) }}</strong><small>{{ browserItems.length }} 项文件</small></div><button class="icon-btn storage-browser__close" type="button" aria-label="关闭附件查看器" @click="closeBrowser"><X :size="18" /></button></header>
        <div class="storage-browser__toolbar"><div class="storage-browser__tabs"><button type="button" :class="{ active: browserTab === 'orphan' }" @click="setBrowserTab('orphan')">待处理 <b>{{ report.orphanAttachments.length }}</b></button><button type="button" :class="{ active: browserTab === 'quarantine' }" @click="setBrowserTab('quarantine')">清理站 <b>{{ report.quarantinedAttachments.length }}</b></button></div><span class="storage-browser__toolbar-meta"><span class="storage-browser__count">{{ browserTab === 'quarantine' ? '可恢复保护已开启' : '尚未执行删除' }}</span><span class="storage-browser__help"><button type="button" aria-label="查看附件维护说明" :aria-describedby="'storage-browser-help'" title="查看附件维护说明"><Info :size="15" /></button><span id="storage-browser-help" class="storage-browser__tooltip" role="tooltip"><strong>{{ browserTab === 'orphan' ? '待处理附件' : '清理站' }}</strong><span>{{ browserTab === 'orphan' ? '未被任务、备注或回收站引用。移入清理站不会直接删除，可随时恢复。' : '文件仍可恢复；仅在永久删除确认后，才会释放本机空间。' }}</span></span></span></span></div>
        <div class="storage-browser__list"><p class="storage-browser__list-label">{{ browserTab === 'orphan' ? '待整理的文件' : '暂存的文件' }} · {{ browserItems.length }} 项</p><article v-for="item in browserPageItems" :key="item.id" class="storage-item"><button v-if="item.isImage && previews[item.relativePath]" class="storage-item__preview" type="button" :title="`查看 ${item.name}`" @click="openPreview(item)"><img :src="previews[item.relativePath]" :alt="item.name" /></button><span v-else class="storage-item__file"><File :size="18" /></span><span><strong :title="item.relativePath">{{ item.name }}</strong><small>{{ bytes(item.sizeBytes) }} · {{ item.relativePath }}</small></span><span class="storage-item__actions"><button v-if="browserTab === 'orphan'" class="small-btn" type="button" :disabled="acting" @click="quarantine(item)">移入清理站</button><template v-else><button class="small-btn" type="button" :disabled="acting" @click="restore(item)">恢复文件</button><button class="text-btn danger" type="button" :disabled="acting" @click="requestPurge([item])">永久删除</button></template></span></article></div>
        <footer v-if="browserPageCount > 1" class="storage-browser__pagination storage-browser__pagination--workbench"><button class="text-btn" type="button" :disabled="browserPage === 0" @click="changeBrowserPage(-1)">上一页</button><span>第 {{ browserPage + 1 }} / {{ browserPageCount }} 页 · 每页 {{ browserPageSize }} 项</span><button class="text-btn" type="button" :disabled="browserPage + 1 >= browserPageCount" @click="changeBrowserPage(1)">下一页</button></footer>
      </section>
    </div>
  </Teleport>
  <Teleport to="body">
    <div v-if="migrationBrowserOpen" class="storage-browser-layer" @keydown.esc.stop="migrationBrowserOpen = false">
      <button class="storage-browser-layer__scrim" type="button" aria-label="关闭迁移备份查看器" @click="migrationBrowserOpen = false"></button>
      <section class="storage-browser storage-browser--with-summary" role="dialog" aria-modal="true" aria-labelledby="migration-backup-title">
        <header class="storage-browser__hero"><span class="storage-browser__hero-icon"><HardDrive :size="21" /></span><div class="storage-browser__hero-copy"><span>升级保护</span><h2 id="migration-backup-title">历史迁移备份</h2><small>这些文件用于旧版本数据升级时的回退，不属于可恢复的当前快照。</small></div><div class="storage-browser__hero-metric"><strong>{{ bytes(report.migrationBackupBytes) }}</strong><small>{{ report.migrationBackups.length }} 项文件</small></div><button class="icon-btn storage-browser__close" type="button" aria-label="关闭迁移备份查看器" @click="migrationBrowserOpen = false"><X :size="18" /></button></header>
        <div class="storage-browser__list"><p class="storage-browser__list-label">可清理的迁移备份 · {{ report.migrationBackups.length }} 项</p><article v-for="item in report.migrationBackups" :key="item.id" class="storage-item"><span class="storage-item__file"><HardDrive :size="18" /></span><span><strong :title="item.name">{{ item.name }}</strong><small>{{ bytes(item.sizeBytes) }} · {{ formatDate(item.modifiedAt) }}</small></span><span class="storage-item__actions"><button class="text-btn danger" type="button" :disabled="acting" @click="requestMigrationPurge([item])">永久删除</button></span></article></div>
      </section>
    </div>
  </Teleport>
  <ConfirmDialog :visible="pendingPurge.length > 0" title="确认永久删除？" :message="`将从本机删除 ${pendingPurge.length} 项文件，共 ${bytes(pendingPurgeBytes)}。删除后无法恢复。`" tag="清理站" :details="purgeDetails" :confirm-text="acting ? '正在删除…' : `永久删除 ${pendingPurge.length} 项`" cancel-text="暂不删除" type="danger" :z-index="3400" @confirm="confirmPurge" @cancel="pendingPurge = []" />
  <ConfirmDialog :visible="pendingMigrationPurge.length > 0" title="删除历史迁移备份？" :message="`将永久删除 ${pendingMigrationPurge.length} 个升级前的历史副本，共 ${bytes(pendingMigrationPurgeBytes)}。它们不能用于当前恢复点恢复，删除后无法撤销。`" tag="历史迁移备份" :details="migrationPurgeDetails" :confirm-text="acting ? '正在删除…' : `永久删除 ${pendingMigrationPurge.length} 项`" cancel-text="暂不删除" type="danger" :z-index="3400" @confirm="confirmMigrationPurge" @cancel="pendingMigrationPurge = []" />
</template>

<script setup>
import { computed, ref } from 'vue'
import { ArchiveRestore, Database, File, FolderArchive, HardDrive, Image, Info, ShieldCheck, Trash2, UserRound, X } from 'lucide-vue-next'
import { useTaskStore } from '@/stores/task'
import { deleteMigrationBackups, purgeQuarantinedAttachments, quarantineOrphanAttachments, readAttachment, readQuarantinedAttachment, restoreQuarantinedAttachments, scanStorageHealth } from '@/services/platform'
import ImageLightbox from './ImageLightbox.vue'
import ConfirmDialog from './ConfirmDialog.vue'

const store = useTaskStore()
defineEmits(['open-security'])
const report = ref(null); const loading = ref(false); const acting = ref(false); const previews = ref({}); const previewOpen = ref(false); const previewImages = ref([]); const previewIndex = ref(0); const browserOpen = ref(false); const browserTab = ref('orphan'); const browserPage = ref(0); const pendingPurge = ref([]); const migrationBrowserOpen = ref(false); const pendingMigrationPurge = ref([])
const retentionDays = [7, 30, 60, 90, 180, 365]; const browserPageSize = 30
const bytes = (value = 0) => value < 1024 ? `${value} B` : value < 1048576 ? `${(value / 1024).toFixed(1)} KB` : `${(value / 1048576).toFixed(1)} MB`
const reclaimableBytes = computed(() => (report.value?.orphanBytes || 0) + (report.value?.quarantinedBytes || 0))
const orphanTypeSummary = computed(() => { const value = report.value; return [value?.orphanImageBytes && `图片 ${bytes(value.orphanImageBytes)}`, value?.orphanFileBytes && `文件 ${bytes(value.orphanFileBytes)}`].filter(Boolean).join(' · ') })
const categories = computed(() => { const value = report.value; if (!value) return []; return [{ id: 'database', label: '任务数据', description: '任务、清单与设置', bytes: value.databaseBytes, icon: Database }, { id: 'images', label: '已用图片', description: '被任务或备注引用', bytes: value.referencedImageBytes, icon: Image }, { id: 'files', label: '已用文件', description: '被任务引用的非图片附件', bytes: value.referencedFileBytes, icon: File }, { id: 'orphan', label: '待处理附件', description: '未被引用，可移入清理站', bytes: value.orphanBytes, icon: Trash2, reclaimable: true }, { id: 'quarantine', label: '清理站', description: '已暂存，可恢复或永久删除', bytes: value.quarantinedBytes, icon: Trash2, reclaimable: true }, { id: 'profile', label: '个人资料', description: '头像等本机资料', bytes: value.profileBytes, icon: UserRound }, { id: 'backup', label: '本机恢复点', description: '可恢复的数据快照', bytes: value.backupBytes, icon: ShieldCheck }, { id: 'migration-backup', label: '历史迁移备份', description: '升级前自动保存的兼容性副本', bytes: value.migrationBackupBytes, icon: HardDrive, reclaimable: true }, { id: 'other', label: '其他应用数据', description: '应用运行所需文件', bytes: value.otherBytes, icon: HardDrive }].filter(item => item.bytes > 0) })
const browserItems = computed(() => browserTab.value === 'orphan' ? (report.value?.orphanAttachments || []) : (report.value?.quarantinedAttachments || []))
const browserBytes = computed(() => browserItems.value.reduce((total, item) => total + item.sizeBytes, 0))
const browserPageCount = computed(() => Math.max(1, Math.ceil(browserItems.value.length / browserPageSize)))
const browserPageItems = computed(() => browserItems.value.slice(browserPage.value * browserPageSize, (browserPage.value + 1) * browserPageSize))
const pendingPurgeItems = computed(() => (report.value?.quarantinedAttachments || []).filter(item => pendingPurge.value.includes(item.id)).slice(0, 3))
const pendingPurgeBytes = computed(() => (report.value?.quarantinedAttachments || []).filter(item => pendingPurge.value.includes(item.id)).reduce((total, item) => total + item.sizeBytes, 0))
const purgeDetails = computed(() => [{ label: '文件数量', value: `${pendingPurge.value.length} 项`, type: 'danger' }, { label: '可释放空间', value: bytes(pendingPurgeBytes.value), type: 'info' }, { label: '文件示例', value: pendingPurgeItems.value.map(item => item.name).join('、') || '无', type: 'default' }])
const pendingMigrationPurgeItems = computed(() => (report.value?.migrationBackups || []).filter(item => pendingMigrationPurge.value.includes(item.id)))
const pendingMigrationPurgeBytes = computed(() => pendingMigrationPurgeItems.value.reduce((total, item) => total + item.sizeBytes, 0))
const migrationPurgeDetails = computed(() => [{ label: '备份数量', value: `${pendingMigrationPurge.value.length} 项`, type: 'danger' }, { label: '可释放空间', value: bytes(pendingMigrationPurgeBytes.value), type: 'info' }, { label: '文件示例', value: pendingMigrationPurgeItems.value.slice(0, 3).map(item => item.name).join('、') || '无', type: 'default' }])
async function scan () { loading.value = true; try { report.value = await scanStorageHealth(); previews.value = {}; pendingPurge.value = []; pendingMigrationPurge.value = []; browserPage.value = 0 } catch (error) { store.showNotice(error?.message || '扫描本机存储失败', 'error') } finally { loading.value = false } }
async function run (action, text) { if (!report.value) return; acting.value = true; try { const result = await action(); store.showNotice(`${text} ${result.affectedCount} 项，${bytes(result.affectedBytes)}`, 'success'); await scan() } catch (error) { store.showNotice(error?.message || '操作失败', 'error') } finally { acting.value = false } }
const quarantine = item => run(() => quarantineOrphanAttachments([item.relativePath]), '已移入清理站'); const quarantineAll = () => run(() => quarantineOrphanAttachments(report.value.orphanAttachments.map(item => item.relativePath)), '已移入清理站'); const restore = item => run(() => restoreQuarantinedAttachments([item.id]), '已恢复'); const restoreAll = () => run(() => restoreQuarantinedAttachments(report.value.quarantinedAttachments.map(item => item.id)), '已恢复')
function requestPurge (items) { pendingPurge.value = items.map(item => item.id) }; function confirmPurge () { if (acting.value || !pendingPurge.value.length) return; return run(() => purgeQuarantinedAttachments(pendingPurge.value), '已永久删除') }
function requestMigrationPurge (items) { pendingMigrationPurge.value = items.map(item => item.id) }; function confirmMigrationPurge () { if (acting.value || !pendingMigrationPurge.value.length) return; return run(() => deleteMigrationBackups(pendingMigrationPurge.value), '已删除历史迁移备份') }
async function openBrowser (tab) { browserTab.value = tab; browserPage.value = 0; browserOpen.value = true; await hydratePreviews(browserItems.value, tab) }; async function setBrowserTab (tab) { browserTab.value = tab; browserPage.value = 0; await hydratePreviews(browserItems.value, tab) }; function changeBrowserPage (delta) { browserPage.value = Math.max(0, Math.min(browserPageCount.value - 1, browserPage.value + delta)) }; function closeBrowser () { browserOpen.value = false; pendingPurge.value = [] }
async function hydratePreviews (items, source = 'orphan') { const pairs = await Promise.all(items.filter(item => item.isImage).map(async item => [item.relativePath, await (source === 'quarantine' ? readQuarantinedAttachment(item.id) : readAttachment(item.relativePath)).catch(() => '')])); previews.value = { ...previews.value, ...Object.fromEntries(pairs.filter(([, url]) => url)) } }
function openPreview (item) { const images = browserItems.value.filter(candidate => candidate.isImage).map(candidate => previews.value[candidate.relativePath]).filter(Boolean); previewIndex.value = images.indexOf(previews.value[item.relativePath]); previewImages.value = images; previewOpen.value = true }
function formatDate (value) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '未知时间' : date.toLocaleString('zh-CN', { dateStyle: 'medium', timeStyle: 'short' }) }
</script>
